config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  root 'articles#index'

  resources :articles

  get 'tag/:id', to:'tags#show'

  get 'backend', to: 'backend#index'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable, :recoverable
  devise :database_authenticatable, :registerable, :recoverable,
          :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_and_belongs_to_many :tag, :uniq => true
	validates :title, presence: true,
                    length: { minimum: 5 }

    has_attached_file :pic, :styles => { :small => "240>" },
    					:url  => "/article_cover/:id/:style_:basename.:extension",
    					:path => ":rails_root/public/article_cover/:id/:style_:basename.:extension"

    validates_attachment_content_type :pic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 6.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :article, :uniq => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  #http_basic_authenticate_with name: "admin", password: "1", except: [:index, :show]

  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @articles = Article.all.order(created_at: :desc)
    @tags = Tag.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :text, :pic))
    tag_arr = params[:article][:tag].split(',')


    if @article.save
      Article.transaction do
        tag_arr.each do |name|
          # create a new tag only if tag.name not exist
          tag = Tag.find_or_create_by(name: name.strip! || name)

          # Update tag blog_count
          if tag.blog_count
            tag.blog_count += 1
          else
            tag.blog_count = 1
          end
          tag.save

          # Push current to current article
          @article.tag.push(tag)
        end
      end
      redirect_to @article
    else
      render 'new'
    end

  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    # Clear all tags associated with article to edit
    if not @article.tag.nil?
      @article.tag.each do |t|
        t.blog_count -= 1
        if t.blog_count == 0
          t.delete
        else
          t.save
        end
      end
    end
    @article.tag.delete_all

    tag_arr = params[:article][:tag].split(',')

    if @article.update(params.require(:article).permit(:title, :text, :pic))
      Article.transaction do
        tag_arr.each do |name|
          # create a new tag only if tag.name not exist
          tag = Tag.find_or_create_by(name: name.strip! || name)

          # Update tag blog_count
          if tag.blog_count
            tag.blog_count += 1
          else
            tag.blog_count = 1
          end
          tag.save

          # Push current to current article
          @article.tag.push(tag)
        end
      end
      redirect_to @article
    else
      render 'edit'
    end
  end

  def upload
    uploaded_io = params[:article][:img]
    File.open(Rails.root.join('public', 'uploads',
                              uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  def destroy
    @article = Article.find(params[:id])

    if not @article.tag.nil?
      @article.tag.each do |t|
        t.blog_count -= 1
        if t.blog_count == 0
          t.delete
        else
          t.save
        end
      end
    end
    @article.destroy

    redirect_to articles_path
  end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

	before_action :authenticate_admin!
	def index
		@articles = Article.all.order(created_at: :desc)
	@tags = Tag.all
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  	@current_tag = Tag.find(params[:id])
  	@tags = Tag.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
	    params.permit(:title, :text)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= javascript_include_tag 'article_edit' %>


<% if params.has_key?(:id) %>
    <% action = "update" %>
    <% method = "patch" %>
<% else %>
    <% action = "create" %>
    <% method = "post" %>
<% end %>


<%= form_for @article, url: {action: action},
             html: {class: "pure-form pure-form-stacked", method: method, :multipart => true} do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <%= f.label :text, "Text" %>
    <%= f.cktext_area :text, rows: 20 %>
    <%= f.label :tag, "Tag" %>
    <%= f.text_field :tag, value: @article.tag.map { |c| c.name }.join(',') %>
    <%= f.label :pic, "Upload Cover Image" %>
    <%= f.file_field :pic %>
    <!-- <ul id="cover-image">
      <li><a href="javascript:void(0)" id="img-refresh">refresh</a></li>
    </ul> -->


    <%= f.submit "Submit", class: "pure-button pure-button-primary" %>

<% end %>

app/views/articles/edit.html.erb
<%= render 'shared/header' %>

<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

<%= render 'shared/footer' %>

app/views/articles/index.html.erb
<%= render 'shared/header' %>
	<div class="left-container">
	  <% @articles.each do |article| %>
	      <%= render 'shared/list_item', article: article %>
	  <% end %>
	  
	</div>

	<%= render 'shared/side_bar', tags: @tags, articles: @articles %>

<%= render 'shared/footer' %>

app/views/articles/new.html.erb
<%= render 'shared/header' %>

<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

<%= render 'shared/footer' %>

app/views/articles/show.html.erb
<%= stylesheet_link_tag 'highlight/monokai_sublime' %>
<%= javascript_include_tag 'highlight/highlight.pack'  %>
<%= javascript_include_tag 'article_view'  %>
<%= javascript_include_tag 'toc.min' %>

<% @title = @article.title + ' - ' %>


<%= render 'shared/header' %>

<div class="left-container article-view-left">
  <h1><%= @article.title %></h1>

  <article><%= @article.text.html_safe %></article>

  <%= link_to 'Back', articles_path %>
</div>

<div class="side-bar article-view-right">
  <div class="side-box toc">
    <h2>INDEX</h2>

    <hr>
    <div id="toc"></div>
  </div>

  <div class="side-box">
    <h2>TAGS</h2>
    <hr>
    <ul class="tag-cloud">
      <% @article.tag.each do |t| %>
          <li><%= link_to(t.name, controller: 'tags', action: 'show', id: t.id)  %></li>
      <% end %>

    </ul>
  </div>

</div>


<%= render 'shared/footer' %>

app/views/backend/_list_item.html.erb
<div class="list-item">
	<h2 class="post-title"><%= link_to article.title, article_path(article) %></h2>
	<ul class="subtitle">
		<li>
			<%= article.created_at.strftime("%B %d, %Y") %>
		    <span><%= link_to 'Edit', edit_article_path(article) %></span>
		    <span><%= link_to 'Destroy', article_path(article),
		                        method: :delete, data: { confirm: 'Are you sure?' } %></span>
		</li>
	</ul>

    <% if article.pic? %>
      <%= image_tag article.pic.url(:small) %>
    <% end %>
	<section>

		<% if not article.text.nil? %>
			<% if not article.pic? %>
	    		<%= truncate_html(sanitize(article.text, {:tags=>['a', 'p']}), length: 450, omission: '&nbsp...') %>
	    	<% else %>
	    		<%= truncate_html(sanitize(article.text, {:tags=>['a']}), length: 380, omission: '&nbsp...') %>
	    	<% end %>
    	<% end %> 
	</section>

	<ul class="tags">
		<% article.tag.each do |t| %>
			<li><%= link_to(t.name, controller: 'tags', action: 'show', id: t.id)  %></li>
		<% end %>
	</ul>
</div>

app/views/backend/index.html.erb
<%= render 'shared/header' %>

<div class="left-container">
  <% @articles.each do |article| %>
      <%= render 'list_item', article: article %>
  <% end %>
  
</div>

<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %> Wenhan Lu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'w-logo-small.png' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_about.html.erb
<div class="left">

	<div class="about-main left">
		<div class="about-title">
			<p style="font-family: 'VT323'; font-size: 68px; ">Hello! This is Wenhan Lu</p>
		</div>
		<div class="about-describe">
			<blockquote>Welcome! I'm a software enginner working for Amazon Web Service S3 team. My job is to build
				data intelligence platform for the largest cloud storage in the world!<p></p></blockquote>
			<h2>Things describe me</h2>
			<ul class="describe-list">
				<li>Former Professional Swimmer</li>
				<li>Hadoop Developer</li>
				<li>World Wide Traveler</li>
				<li>CMU Alumni</li>
			</ul>
		</div>

		<div class="clear"></div>
		<h2>Find me here</h2>
		<div class="google-map">
			<div id="gmap_canvas"></div>
			<style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
		</div>
	</div>

	
</div>

<div class="side-bar">
  <div class="side-box">
    <h2>CONTACT</h2>
    <hr>
    <a href="mailto://wenhanlu.cmu@gmail.com">wenhanlu.cmu@gmail.com</a>
  </div>

</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript"> function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(47.6154922,-122.3356412),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(47.6154922, -122.3356412)});infowindow = new google.maps.InfoWindow({content:"<b>Amazon Blackfoot</b><br/>1918 8th Ave<br/>98101 Seattle" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);
</script>

app/views/shared/_admin.html.erb
<br/>
<%= link_to 'New article', new_article_path %>&nbsp;
<%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>

app/views/shared/_experience.html.erb
<div class="resume-left">
    <h2>Work Experience</h2>
    <div class="h2-separator"></div>
    <ul class="clear">
      <li class="left">
        <%= image_tag '/experience/google.jpg' %>
        <div class="exp-info">
          <h3>Software Engineer in Google</h3>
          <span>Jan 2016 - present</span>
          <p>Working for data center software team automating new server turnups in Google's data center.</p>
        </div>

      </li>
      <li class="left">
        <%= image_tag '/experience/aws.png' %>
        <div class="exp-info">
          <h3>Software Engineer in Amazon Web Service</h3>
          <span>July 2015 - Jan 2016</span>
          <p>Worked for S3 Data Intelligence team. Building big data platform infrastructure for S3 team internal use.
            We plan to provide data intelligence product to our customers who store massive data in S3.</p>
        </div>

      </li>
      <li class="left">
        <%= image_tag '/experience/amazon.png' %>
        <div class="exp-info">
          <h3>Software Engineer Intern in Amazon.com</h3>
          <span>May 2014 - August 2014</span>
          <p>Worked in Risk Platform Service team. Developed a data visualization tool for machine learning model
            comparisons.
          </p>
        </div>

      </li>
    </ul>

  <h2>Education</h2>
  <div class="h2-separator"></div>
  <ul class="clear edu">
    <li>
      <h3>Carnegie Mellon University</h3>
      <span>M.S. Information Security <i>(2013 - 2015)</i></span>
    </li>
    <li>
      <h3>Tianjin University</h3>
      <span>B.S. Software Engineering  <i>(2008 - 2012)</i></span>
    </li>
  </ul>

    <h2>Patent</h2>
    <div class="h2-separator"></div>
    <p class="clear">Undergraduate work. Use visual analytics to find out malicious user in web access log.</p>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/tP9iXpYGdDc" frameborder="0" allowfullscreen></iframe>



</div>

<div class="skill right">
    <h2>Skills</h2>
    <div class="h2-separator"></div>
    <ul class="clear">
      <li>
        <h4>Java</h4>
        <div class="rate p-80" >80%</div>
      </li>
      <li>
        <h4>Hadoop</h4>
        <div class="rate p-80" >80%</div>
      </li>
      <li>
        <h4>Ruby on Rails</h4>
        <div class="rate p-75" >75%</div>
      </li>
      <li>
        <h4>Bash</h4>
        <div class="rate p-70" >70%</div>
      </li>
      <li>
        <h4>Python</h4>
        <div class="rate p-60" >60%</div>
      </li>
      <li>
        <h4>C/C++</h4>
        <div class="rate p-60" >60%</div>
      </li>
      <li>
        <h4>PHP</h4>
        <div class="rate p-50" >50%</div>
      </li>
      <li>
        <h4>Spark</h4>
        <div class="rate p-50" >50%</div>
      </li>
    </ul>

</div>

app/views/shared/_footer.html.erb
		</div>

		<div class="section-resume">
			<%= render "shared/experience" %>
		</div>

	</div>
	<a href="#" class="b-top"></a>
</div>

<script>
jQuery(document).ready(function($){
	// browser window scroll (in pixels) after which the "back to top" link is shown
	var offset = 20,
		//browser window scroll (in pixels) after which the "back to top" link opacity is reduced
		offset_opacity = 1200,
		//duration of the top scrolling animation (in ms)
		scroll_top_duration = 300,
		//grab the "back to top" link
		$back_to_top = $('.b-top');

	//hide or show the "back to top" link
	$(window).scroll(function(){
		( $(this).scrollTop() > offset ) ? $back_to_top.addClass('b-visible') : $back_to_top.removeClass('b-visible');
	});

	//smooth scroll to top
	$back_to_top.on('click', function(event){
		event.preventDefault();
		$('body,html').animate({
			scrollTop: 0 ,
		 	}, scroll_top_duration
		);
	});

});

</script>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag 'slick' %>
<%= javascript_include_tag "slick.min" %>

<script>
	$(function(){	
		var slider = $(".slider");
		slider.slick({
			arrows: false,
			initialSlide: 1,
			draggable: false
		});

		$(".tab-about").click(function(){
			slider.slick('slickGoTo', 0);
			var curr = $(".tab-about");
			curr.siblings().removeClass("selected");
			curr.addClass("selected");
		});
		$(".tab-blog").click(function(){
			var curr = $(".tab-blog");
			if (curr.hasClass("selected")) {
				window.location = "/";
			} else {
				slider.slick('slickGoTo', 1);
				curr.siblings().removeClass("selected");
				curr.addClass("selected");
			}

		});
		$(".tab-resume").click(function(){
			slider.slick('slickGoTo', 2);
			var curr = $(".tab-resume");
			curr.siblings().removeClass("selected");
			curr.addClass("selected");
		});
	});
	
</script>

<div class="header lazy" data-original="wooden-background.jpg">
	<%= image_tag "/avatar/normal.jpg", :class => "avatar"%>
	<h1><a href="/">Wenhan Lu</a></h1>
	<h2>Software Engineer @ Google</h2>
	<p> CMU / Distributed System / Cloud / Hadoop </p>
	<div class="social">
		<a class="twitter" href="http://twitter.com/vince_lv" target="_blank">Twitter</a>
		<a class="linkedin" href="https://www.linkedin.com/in/wenhanl" target="_blank">LinkedIn</a>
		<a class="github" href="http://github.com/wenhanl" target="_blank">Github</a>
		<a class="email" href="mailto:wenhanlu.cmu@gmail.com" target="_blank">Email me</a>
	</div>
</div>

<div class="nav">
	<div class="container">
		
		<nav class="cl-effect-4">
			<a href="javascript:void(0)" class="tab-about">About</a>
			<a href="javascript:void(0)"  class="selected tab-blog">Blog</a>
			<a href="javascript:void(0)" class="tab-resume">Experience</a>
		</nav>

	</div>
</div>

<div class="container main top-to-bottom" data-no-turbolink>
	<div class="slider" data-slick='{"slidesToShow": 1, "slidesToScroll": 1}'>

	<div class="section-about">
		<%= render "shared/about" %>
	</div>

	<div class="section-blog">

app/views/shared/_list_item.html.erb
<div class="list-item">
	<h2 class="post-title"><%= link_to article.title, article_path(article) %></h2>
	<ul class="subtitle"><li><%= article.created_at.strftime("%B %d, %Y") %></li></ul>

    <% if article.pic? %>
      <%= image_tag article.pic.url(:small) %>
    <% end %>
	<section>

		<% if not article.text.nil? %>
			<% if not article.pic? %>
	    		<%= truncate_html(sanitize(article.text, {:tags=>['a', 'p']}), length: 400, omission: '&nbsp...') %>
	    	<% else %>
	    		<%= truncate_html(sanitize(article.text, {:tags=>['a']}), length: 300, omission: '&nbsp...') %>
	    	<% end %>
    	<% end %> 
	</section>

	<ul class="tags">
		<% article.tag.each do |t| %>
			<li><%= link_to(t.name, controller: 'tags', action: 'show', id: t.id)  %></li>
		<% end %>
	</ul>
</div>

app/views/shared/_side_bar.html.erb
<div class="side-bar">

	<h2>TAGS</h2>
	<ul class="tag-cloud">
		<% tags.each do |t| %>
			<li>
				<%= link_to(t.name, controller: 'tags', action: 'show', id: t.id)  %>
			</li>
		<% end %>
		
	</ul>
	
	<% if admin_signed_in? && articles %>
		<%= render 'shared/admin', articles: @articles %>
	<% end %>
</div>

app/views/tags/show.html.erb
<%= render 'shared/header' %>

<div class="left-container">
	<h1> Tag: #<%= @current_tag.name %> </h1>
	<% if not @current_tag.nil? %>
		<% @current_tag.article.each do |article| %>
	      <%= render 'shared/list_item', article: article %>
	  	<% end %>
	<% end %>
</div>

<%= render 'shared/side_bar', tags: @tags, articles: nil %>

<%= render 'shared/footer' %>